Repository Fourteen98/Voicer-Parteva, pull requests merged in 2021-07, with the labels that each got.

#21 Fourteen98.voicer parteva key info
  lambda/lambda_function.py
  skill-package/interactionModels/custom/en-GB.json
Labels: enhancement

#22 Fourteen98.voicer parteva key info
  lambda/lambda_function.py
  skill-package/interactionModels/custom/en-GB.json
Labels: enhancement

#25 fixed WhyCreateVoicerIntent did not evaluate well, and some minor cha…
  lambda/lambda_function.py
  skill-package/interactionModels/custom/en-GB.json
Labels: bug

#23 Smart8099.ktu key info
  lambda/lambda_function.py
  skill-package/interactionModels/custom/en-GB.json
Labels: enhancement

#26 First PR from master to main
  lambda/lambda_function.py
  skill-package/interactionModels/custom/en-GB.json
Labels: enhancement

#38 Update index.md
  index.md
Labels: documentation

#36 Fourteen98.information about fbms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  lambda/lambda_function.py
  skill-package/interactionModels/custom/en-GB.json
Labels: enhancement

#39 Smart8099.ktu key info
  lambda/lambda_function.py
  skill-package/interactionModels/custom/en-GB.json
Labels: enhancement

#52 Smart8099.ktu contact key info
  lambda/lambda_function.py
  skill-package/interactionModels/custom/en-GB.json
Labels: enhancement

#54 Resolve issues in json model {},
  skill-package/interactionModels/custom/en-GB.json
Labels: bug
